Webdriver library
browserstack/browserstack-examples-junit5 pull request #8
Opened 2021-12-14 12:52 UTC by smangarole

Tested the jenkins job. Looks good.

2022-01-04 05:47 UTC, samirans89 requested changes

2022-01-04 05:47 UTC, samirans89 commented on allure-generate.bat
> +if %CI% != true (
is this file needed in GitHub or is auto generated when the project is built?

2022-01-04 05:47 UTC, samirans89 commented on allure-generate.sh
> +if [ "$CI" != true ] ; then
is this file needed in GitHub or is auto generated when the project is built?

2022-01-04 05:47 UTC, samirans89 commented on build.gradle
> +dependencies {
webdriver lib?

2022-01-04 05:47 UTC, samirans89 commented on src/main/java/com/browsersatck/examples/pages/Checkout.java
> +    private static final String POST_CODE = "400068";
anonymise names and addresses.

2022-01-04 05:47 UTC, samirans89 commented on src/main/java/com/browsersatck/examples/pages/Login.java
> +import com.browsersatck.examples.utils.WebDriverWaitUtil;
correct package name spell error for browserstack.

2022-01-04 05:47 UTC, samirans89 commented on src/main/java/com/browsersatck/examples/pages/Login.java
> +    private static final String USER_INPUT_XPATH = "//input[@id='react-select-2-input']";
replace with CSS

input[id='react-select-2-input']

2022-01-04 05:47 UTC, samirans89 commented on src/main/java/com/browsersatck/examples/pages/Login.java
> +    private static final String PASSWORD_INPUT_XPATH = "//*[@id=\"react-select-3-input\"]";
replace with CSS
[id='react-select-3-input']

2022-01-04 05:47 UTC, samirans89 commented on src/main/java/com/browsersatck/examples/pages/Offers.java
> +        throw new UnsupportedOperationException("Method is unimplemented.");
do we want to keep this open and unimplemented?

2022-01-04 05:47 UTC, samirans89 commented on src/main/java/com/browsersatck/examples/pages/Orders.java
> +    private static final String PRODUCT_COST_XPATH = "//span[@class='a-size-small a-color-price']";
Replace with CSS:
span[class='a-size-small a-color-price']

2022-01-04 05:47 UTC, samirans89 commented on src/main/java/com/browsersatck/examples/utils/LoggedInNavBarComponent.java
> +    private static final String PRODUCT_COST_XPATH = "//span[@class='a-size-small a-color-price']";
replace with CSS

span[class='a-size-small a-color-price']

2022-01-04 05:47 UTC, samirans89 commented on src/main/java/com/browsersatck/examples/utils/NavBarComponent.java
> +    private static final String USER_INPUT_XPATH = "//input[@id='react-select-2-input']";
replace with CSS

input[id='react-select-2-input']

2022-01-04 05:47 UTC, samirans89 commented on src/test/java/com/browserstack/examples/helpers/Constants.java
> +        public static final String RELOAD_SPINNER_XPATH = "//div[@class='spinner lds-ring']";
replace with CSS

div[class='spinner lds-ring']

2022-01-04 05:47 UTC, samirans89 commented on src/test/java/com/browserstack/examples/helpers/Constants.java
> +        public static final String PRODUCT_COST_XPATH = "//span[@class='a-size-small a-color-price']";
Replace with CSS.

span[class='a-size-small a-color-price']

2022-01-04 05:47 UTC, samirans89 commented on src/test/java/com/browserstack/examples/helpers/Constants.java
> +        public static final String FAVOURITE_BUTTON_XPATH = "//div[@class='shelf-stopper']";
Replace with CSS

div[class='shelf-stopper']

2022-01-04 05:47 UTC, samirans89 commented on src/test/java/com/browserstack/examples/helpers/Constants.java
> +        public static final String FAVOURITE_BUTTON_CLICKED_XPATH = "//button[@class='MuiButtonBase-root MuiIconButton-root Button clicked ']";
Replace with CSS
button[class='MuiButtonBase-root MuiIconButton-root Button clicked ']

2022-01-14 03:08 UTC, raveerocks commented on build.gradle
> +dependencies {
Added for allure plugin

2022-01-17 14:13 UTC, samiran-bs approved these changes

2022-01-17 14:14 UTC, merged